### ISSUE TITLE
`subview.switchTo()` 接口接受的两个回调函数的命名应和事件接口保持一致

### ISSUE THREAD

**Issue by zpbx** [cssmagic/subview#5]
比如： `beforeShow` → `subviewBeforeShow`（其它类推）

**Comment by cssmagic** [comment]
打算给事件名增加命名空间，这样就不会出现事件名在各处不一致的问题了。

需要注意的是，jQuery 和 Zepto 在事件命名空间的行为上可能不一致，参：
http://amazeui.org/getting-started/javascript#javascript

但看了 Zepto 源码后，感觉貌似又是兼容的。待测。

**Comment by cssmagic** [comment]
已另开 #8，因此这个 issue 先关了。
